### ISSUE TITLE
Create a personal wiki page

### ISSUE THREAD

**Issue by burakilkayakgun** [bounswe/bounswe2019group3#1]
- [x]  Samet Demir  
- [x]  Egemen Kaplan  
- [x]  Cihat Kapusuz
- [x]  Burak İlkay Akgün
- [x]  Bartu Ören
- [x]  Okan Akısü
- [x]  Ahmet Mert Tahran
- [x]  Yağmur Kahyaoğlu

**Comment by yagmurkahyaoglu** [comment]
Closed
