### ISSUE TITLE
Add profile photos to your accounts

### ISSUE THREAD

**Issue by simitii** [bounswe/bounswe2019group3#2]
We can have a better-looking readme with the photos and your profiles would seem more professional if you have a profile photo.

- [x]  Samet Demir  
- [ ]  Egemen Kaplan  
- [x]  Cihat Kapusuz
- [x]  Burak İlkay Akgün
- [x]  Bartu Ören
- [x]  Orkan Akısü
- [x]  Ahmet Mert Tahran
- [x]  Yağmur Kahyaoğlu
- [x]  Yusuf Sabri Bayrakdar
- [x] Hilal Demir
- [x] Muhammet Ekrem Gezgen

**Comment by cihatkapusuz** [comment]
@ekremgezgen can you add a profile photo to the your github profile?

**Comment by cihatkapusuz** [comment]
@EgemenKaplan can you add a profile photo to the your github profile?
