### ISSUE TITLE
Develop lyrics & song search feature for the backend

### ISSUE THREAD

**Issue by simitii** [bounswe/bounswe2019group3#38]

**Comment by simitii** [comment]
@burakilkayakgun unit test?

**Comment by burakilkayakgun** [comment]
thanks, we forgot that point.

**Comment by merttahran** [comment]
there is a problem on your test case. On different machines, same queries' results are different therefore you should handle it

**Comment by simitii** [comment]
The bug will be fixed with #50. Therefore, I am closing this issue and we can track the progress in the pull request.
