### ISSUE TITLE
Document the questions regarding the requirements

### ISSUE THREAD

**Issue by yagmurkahyaoglu** [bounswe/bounswe2019group3#6]
Document the questions determined at meeting 2 after discussing them with the customer. Edit the [Requirements](https://github.com/bounswe/bounswe2019group3/wiki/Requirements) according to the answers.

- [x] Orkan Akısü
- [ ] Ahmet Mert Tahran
- [x] Yağmur Kahyaoğlu

**Comment by orkana** [comment]
I added wiki page for questions. I'm writing questions for admin right now

**Comment by orkana** [comment]
and expert

**Comment by orkana** [comment]
and student.
Here is the wiki, make changes however you see fit:
https://github.com/bounswe/bounswe2019group3/wiki/Requirement-Questions

**Comment by yagmurkahyaoglu** [comment]
I edited the wiki page for requirements according to the discussions at the customer meeting.
