### ISSUE TITLE
bug report: exam/evaluate does not handle missing answers

### ISSUE THREAD

**Issue by simitii** [bounswe/bounswe2019group3#72]
### /api/language/:language_abbr/exam/evaluate evaluates level determination exam

- handle missing answers
- handle empty string for choice_id & question_id
- try to avoid the following state since it makes unnecessary search:
`question_id_array.findIndex(search_item => search_item == question[i].id); state`

**Comment by simitii** [comment]
in order to clarify the third point:

current implementation has O(n^2) complexity for the question id matching part. However, we could  achieve O(n) complexity by making use of lookup/hash tables. Since JSON is already is a kind of lookup/hash table, we could use it. see: https://stackoverflow.com/a/45267146

here is the idea:
instead of searching on the array again and again, create a lookup table which maps question_id -> choice_id, which is O(n), and then loop through the questions which is also O(n). Therefore, overall complexity could be O(n).

Obviously, it does not help much for the small n values. However, it is useful to think general case from both educational and development perfective.

**Comment by yusufbayrakdar** [comment]
https://github.com/bounswe/bounswe2019group3/commit/f13578b93933597fe440ccbb0c974235bfb120c6
