### ISSUE TITLE
    models.ExamQuestion.belongsTo(models.ExamChoice) or hasOne ?

### ISSUE THREAD

**Issue by buzem** [bounswe/bounswe2019group3#77]
I think we should replace belongs with hasOne in ExamQuestion model?

Pls check: https://gist.github.com/kaizerroll/22d887a6ee2bdf5aec2df3e4b499497e

**Comment by simitii** [comment]
If you check the comments on the given link, you can see the problem.

**Comment by buzem** [comment]
models.ExamChoice.belongsTo(models. ExamQuestion)
OR hasone(models. ExamQuestion)

?

**Comment by simitii** [comment]
the current usage and the following usage are correct since we wanted ExamQuestion table to have answer_id field not the other way around: 
ExamChoice.hasone(ExamQuestion)

**Comment by buzem** [comment]
understood:)
