### ISSUE TITLE
Editing Requirements Page

### ISSUE THREAD

**Issue by buzem** [bounswe/bounswe2019group3#90]
I recently edited the requirements according to Cihat's review, however some points still remained unfixed.Could you please look at the following unfixed points?:

1.1.3.1.11 -> only handwritten materials? The system should provide the corresponding mechanism for a user to write an essay for an exercise (with a simple text-box?)
1.1.3.2 -> It is ok to just show the directory, but we need to clarify it. What does a directory include? Name of the exercise, or other details?

Why only the avatar is changeable? Other parts of the profile are static? For instance, cannot a user change his/her username, or delete an information from the biography?
1.2.1.2 -> what is the “certain amount”?(How should it be defined?)

**Comment by simitii** [comment]
> Why only the avatar is changeable?
avatar and biography are changeable. username is not changeable since it is not necessary and we use username as id. 

@buzem If the biography seems unchangeable on the requirements, please update it accordingly.

**Comment by simitii** [comment]
@yagmurkahyaoglu Would you please handle the rest of the unfixed items?

**Comment by yagmurkahyaoglu** [comment]
For 1.3.2, what should be the scope? Some example exercises for a single level e. g. A1 or all levels?

**Comment by simitii** [comment]
> For 1.1.3.2, what should be the scope? Some example exercises for a single level e. g. A1 or all levels?
this can be devised from the design of Exercise API (see #89) 
user is required to select a language, then we show all the exercises of the lang. and we also provide options to filter exercises by type(reading, listening...) and/or level(A1, B1...)
for each exercise following properties can be shown: title, language, level, type

On a side note: We may need to add TAGS as a filtering option and/or as a property to be shown

**Comment by yagmurkahyaoglu** [comment]
Done. @buzem @simitii can one of you please review the changes so that I can close the issue? thanks.

**Comment by simitii** [comment]
@buzem you're up. By the way, we may ask for further feedback if you like.

**Comment by buzem** [comment]
I checked it, it seemed fine to me
