### ISSUE TITLE
Design and Implementation of User Progress API

### ISSUE THREAD

**Issue by simitii** [bounswe/bounswe2019group3#93]
- Design and Implementation of User Progress API
    - [x] Get progress for an exercise
    - [x] Get overall progress in a given language

**Comment by simitii** [comment]
@yusufbayrakdar Would you please take on this one? Here is a good approach: You design the endpoints(API), share it with me, we discuss about it, we ask for comments from other teams, and then you implement it. OK?

I am not sure what would be a good timeline for this task but it's better to be as early as possible, anyway.

**Comment by yusufbayrakdar** [comment]
I create progress models and endpoints now and update backend-dev branch I will complete these end points ASAP
![Ekran Resmi 2019-12-05 11 13 24](https://user-images.githubusercontent.com/32673244/70216276-43c49280-1750-11ea-8d57-3c60826a8e63.png)

**Comment by simitii** [comment]
@yusufbayrakdar good but if the progress is an integer (number of completed things), we also need to return the total number of things. Or, we could make the progress float (number of completed / total number). I'm not sure which one is better. So, you choose.

**Comment by yusufbayrakdar** [comment]
@simitii I completed implementation progress models, seeders and endpoints (which is in routes/User.js) and I updated exercise evaluate endpoint to be compatible with progress.Please check the changes and if there is no problem close the issue otherwise let me know any existing problem.
https://github.com/bounswe/bounswe2019group3/commit/a7974511f9d26a282935b0c20402e96b1b12ac78

**Comment by simitii** [comment]
@yusufbayrakdar The code seems OK. I assume you have tested.

**Comment by simitii** [comment]
@yusufbayrakdar By the way, please do not forget to merge to master and production branches.

**Comment by simitii** [comment]
@yusufbayrakdar Also, you need to announce the feature on the WhatsApp group(group 3) so that frontend and mobile can be informed.

**Comment by yusufbayrakdar** [comment]
Okey, I will merge and announce it.
