### ISSUE TITLE
Design and Implementation of Writing API

### ISSUE THREAD

**Issue by simitii** [bounswe/bounswe2019group3#94]
- Design and Implementation of Writing API
    - [x] Save writing
    - [x] List the saved writings of a user
    - [x] Get the content of the given writing id
    - [x] Send saved writing to other users for evaluation 
    - [x] Recommendation: Get recommended users for a (writing, user) pair

**Comment by simitii** [comment]
@buzem Would you please take the first two (Save writing & List the saved writings of a user)?
@yusufbayrakdar Would you take the last two (Send saved writing to other users for evaluation & Recommendation: Get recommended users for a (writing, user) pair)?

In the meantime, I plan to take Annotation API but I may assign some of that to you guys later on.

You do not need to hurry about these but I think you should finish these two in 10 days so that we can some time to handle annotation, which may partially dependent on your work here.

This will conclude our work as the backend team.

**Comment by simitii** [comment]
By the way, the sooner the better as usual...

**Comment by buzem** [comment]
I take first 3 ones.

**Comment by simitii** [comment]
@yusufbayrakdar @buzem You should have finished this task by now. If anything missing, finish as soon as possible and close this issue.

**Comment by simitii** [comment]
I redesigned the writing api and fixed its implementation. f0b3c2d2478e0f1bba41f1ee15f92709bcefcd22
Now, only recommendation is left to be done. So, @yusufbayrakdar you're up.

**Comment by yusufbayrakdar** [comment]
I implemented recommendation endpoint.
https://github.com/bounswe/bounswe2019group3/commit/28e302182d67fc6cfcb23f0bbd3e0be417f12533
