### ISSUE TITLE
Improve the exercise seeds

### ISSUE THREAD

**Issue by simitii** [bounswe/bounswe2019group3#96]
Existing seed data is not good enough for a demo. Especially, proper listening exercises are needed. 

The task is to delete existing seeds and create reasonable exercises.
e.g. 1 reading, 1 listening, 1 grammer exercises with 5 questions, 4 answer choices each + 1 writing exercise with a reasonably detailed topic/theme

By the way, existing seeds can be used as a reference.

related seed files to be changed:
https://github.com/bounswe/bounswe2019group3/blob/master/project/backend/seeders/20191116130441-demo-exercise.js
https://github.com/bounswe/bounswe2019group3/blob/master/project/backend/seeders/20191116170343-demo-exercise-question.js
https://github.com/bounswe/bounswe2019group3/blob/master/project/backend/seeders/20191116205944-demo-exercise-choice.js

**Comment by simitii** [comment]
@buzem Can you take on this one?

**Comment by buzem** [comment]
Could you answer me in Whatsapp group ? :)

**Comment by simitii** [comment]
@yusufbayrakdar

**Comment by simitii** [comment]
@buzem what is the status for this task?

**Comment by buzem** [comment]
Sample listening exercise is done.How many questions should an exercise contain?

**Comment by buzem** [comment]
Others are also done, pushed to backend-dev.But there is 2 problems:
1) In reading questions, the paragraph is too long therefore seeding cannot be accomplished properly.
2)For reading and grammer exercises, the model should contain required==false for the media properties, for succesful seeding.

**Comment by simitii** [comment]
> Sample listening exercise is done.How many questions should an exercise contain?

seems good.

> Others are also done, pushed to backend-dev. But there is 2 problems:
> 
> 1. In reading questions, the paragraph is too long therefore seeding cannot be accomplished properly.
>    2)For reading and grammer exercises, the model should contain required==false for the media properties, for succesful seeding.

I see your points. But, do we actually need some change in the model? There can be short paragraphs for reading questions for the first problem. Second, the required field is not necessary since the frontend and mobile teams can infer if the media fields are used or not by checking if they are available or not.

**Comment by simitii** [comment]
By the way, please do not forget the writing exercise, which is defined in the issue description.
